### ISSUE TITLE
开启样式会导致链接中文文本字体不一致的问题

### ISSUE THREAD

**Issue by Twenru-zzh** [ProudBenzene/Blue-Topaz-Legacy#15]
### 测试条件
obsidian版本： v1.4.16
主题：AnuPpuccin
其他css snippets：其他全部关闭
![image](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/84758016/b406304d-38f3-4ef8-9328-2eedd5b817ed)

### 测试现象
- 阅读视图下**关闭**Legacy样式
![image](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/84758016/a467b7e9-8146-4ce1-94f2-f6b083242520)
- 阅读模式下**开启**Legacy样式
![image](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/84758016/cfb06172-56ff-4c9c-a3bc-fe42d61cda45)
- 其他视图**未发现**影响

### style setting设置代码
- 格式化设置后进行的测试
![image](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/84758016/e41f5bc1-14fb-42c8-ae9c-f71326e5911e)

### 需求
感谢大佬的整合样式片段，一些功能样式很方便使用
- [ ] 修复此处问题
- [ ] 在字体与排版、markdown元素这些大模块上添加启用和关闭功能

**Comment by ProudBenzene** [comment]
抱歉，我在一个新库重现了你的设置，但是暂时未能复现这个bug。

<img width="1425" alt="image" src="https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/93238080/10cc4ac8-5f84-4fb9-ad8f-1c2283cbd38f">

请问您使用的legacy片段是最新版本吗？

**Comment by Twenru-zzh** [comment]
问题解决了

我分别下载code里的obsidian文件和release里的文件测试后仍然出现上述情况

但我去霞鹜官网下载安装 霞鹜文楷常规 后链接文本字体就一直了

我之前只安装了[霞鹜文楷屏幕阅读版 / LXGW WenKai Screen](https://github.com/lxgw/LxgwWenKai-Screen)

经过卸载 霞鹜文楷常规 测试后，发现确实是由此原因引起的
