### ISSUE TITLE
callout在不同主题中的适配问题

### ISSUE THREAD

**Issue by kkkkianaaaa** [ProudBenzene/Blue-Topaz-Legacy#16]
在除Anu的主题下，callout的标题显示会少一行，且缺少左侧边框
![QQ图片20231116002630](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/143202602/5eef3294-dcf5-4461-a18c-509505643cac)

在默认主题下，待办框看不出来样子
![Quicker_20231116_202326](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/143202602/ae2cd61b-10ad-48a9-a1c7-343798e3ba0e)
且浅色模式出错
![Quicker_20231116_202654](https://github.com/ProudBenzene/Blue-Topaz-Legacy/assets/143202602/d5120258-bee6-48e2-8080-bb55cdf43c3b)

**Comment by ProudBenzene** [comment]
你好，我已经在最新版本中修复了你提到的部分问题。
1. Callout的问题（标题与边框），需要添加一些针对默认主题的特化适配，但是这些适配会与其他主题产生冲突。由于我不在默认主题中使用Legacy片段，因此我只在Legacy css中将一些对默认主题的适配以注释的形式补充。如有需要可以在css中搜索“默认”进行手动操作。
2. checkbox同理，也需要添加一些针对默认主题的特化适配，我也将其以注释的形式补充在css文件里，如有需要可以在css中搜索“默认”进行手动操作。
3. 浅色模式出错的问题已经得到修复。

**Comment by ProudBenzene** [comment]
新版本将会完全去除对默认主题callout的影响。
